# SGX Demo
# Florent Dufour

demo: configure up ## Configure VM and starts demo
configure: ## Configure the SGX VM
	bash configure.sh
up: ## Starts the cotainers for the demo
	docker-compose up
down: ## Stop the demo
	docker-compose down