.RP no

\" DOCUMENT INFORMATION
.TL
This is the title of the document
.AU
Florent Dufour
.AI
du4
.ND
.so sections/abstract.ms

.so macros.ms

\" TABLE OF CONTENTS

\" BODY OF THE DOCUMENT
.NH 1
Introduction

.so sections/introduction.ms

.NH
Conclusion

.so sections/conclusion.ms

.NH
Mathematics
.EQ
x >= 3 +- 5
.EN

.EQ
define disc `b sup {2} - 4ac`
.EN

.EQ
disc
.EN

.EQ
b sub 3
.EN

.EQ
phi  = {1 + sqrt 5} over 2
.EN

.EQ
s = sqrt {
{sum from i=1 to N ( x sub i - x bar ) sup 2}
over
N-1
}
.EN

.EQ
pi = int from -1 to 1 dx over sqrt { 1 - x sup 2  }
.EN

\" INLINE EQUATIONS
.EQ
delim $$
.EN

.PP
This is a test for inline equation: $x +- b sup 4$
.PP
And another one: $x sup 5$
