.NH 2
Sub section
.PP
Porttitor massa id neque aliquam vestibulum morbi blandit cursus. Amet est placerat in egestas. Sed libero enim sed faucibus turpis in eu mi. Pretium nibh ipsum consequat nisl. Penatibus et magnis dis parturient montes. Vitae turpis massa sed elementum tempus egestas. Iaculis eu non diam phasellus vestibulum lorem sed risus. Non curabitur gravida arcu ac tortor dignissim. Ut sem nulla pharetra diam. Nullam non nisi est sit.
.NH 2
Another sub section
.PP
Fringilla urna porttitor rhoncus dolor purus. Quis enim lobortis scelerisque fermentum dui. Eu mi bibendum neque egestas congue quisque. Felis bibendum ut tristique et egestas quis ipsum. Elit at imperdiet dui accumsan sit. Sed elementum tempus egestas sed sed risus pretium. Cras semper auctor neque vitae. Amet justo donec enim diam vulputate ut pharetra sit. Facilisis sed odio morbi quis commodo odio aenean sed. Consequat ac felis donec et odio pellentesque diam. Libero nunc consequat interdum varius sit amet mattis. Vulputate dignissim suspendisse in est ante in nibh. Amet nulla facilisi morbi tempus iaculis urna id.
.NH 2
Sub body
.PP
Porttitor massa id neque aliquam vestibulum morbi blandit cursus. Amet est placerat in egestas. Sed libero enim sed faucibus turpis in eu mi. Pretium nibh ipsum consequat nisl. Penatibus et magnis dis parturient montes. Vitae turpis massa sed elementum tempus egestas. Iaculis eu non diam phasellus vestibulum lorem sed risus. Non curabitur gravida arcu ac tortor dignissim. Ut sem nulla pharetra diam. Nullam non nisi est sit.
.NH 2
Another sub bidy
.PP
Fringilla urna porttitor rhoncus dolor purus. Quis enim lobortis scelerisque fermentum dui. Eu mi bibendum neque egestas congue quisque. Felis bibendum ut tristique et egestas quis ipsum. Elit at imperdiet dui accumsan sit. Sed elementum tempus egestas sed sed risus pretium. Cras semper auctor neque vitae. Amet justo donec enim diam vulputate ut pharetra sit. Facilisis sed odio morbi quis commodo odio aenean sed. Consequat ac felis donec et odio pellentesque diam. Libero nunc consequat interdum varius sit amet mattis. Vulputate dignissim suspendisse in est ante in nibh. Amet nulla facilisi morbi tempus iaculis urna id.
.NH 1
Another section
.PP
With a
.B bold
word, and even a
.I italic
word or even
.BI "bold italic"
as you can see.
Note that formatting the end after a command is
.B "important" ). (
We can also
.UL "underline some text"
or
.BX "box test" .
How about list ?
.IP \(bu 2
This is a list item
.IP \(bu 2
And another
.IP \(bu 2
and another
.UL
and another other
